version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: ahmad
      POSTGRES_PASSWORD: ahmad
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - jobnet

  backend:
    build:
      context: ./jobtracker
      dockerfile: Dockerfile
      platform: linux/amd64
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jobtracker
      SPRING_DATASOURCE_USERNAME: ahmad
      SPRING_DATASOURCE_PASSWORD: ahmad
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      FRONTEND_URL: http://localhost:5173
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - jobnet

  frontend:
    build:
      context: ./jobtracker-frontend
      dockerfile: Dockerfile
      platform: linux/amd64
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - backend
    networks:
      - jobnet

volumes:
  db-data:

networks:
  jobnet:
    driver: bridge
